spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tiendajofer?useSSL=false&serverTimezone=UTC
    username: mystore
    password: "joferchop"  # Contraseña actualizada
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
